db:
  url: jdbc:postgresql://localhost:5432/Fortune
  username: postgres
  password: k464350g
  hikari:
    max-pool-size: 10
  driver:
    classname: org.postgresql.Driver

env_variables:
  JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8

