db:
  url: jdbc:postgresql://localhost:5432/Fortune
  username: postgres
  password: k464350g
  hikari:
    max-pool-size: 10
  driver:
    classname: org.postgresql.Driver

env_variables:
  JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8

  spring:
    jackson:
      # Date format string or a fully-qualified date format class name. For instance, 'yyyy-MM-dd HH:mm:ss'
      date-format: "yyyy-MM-dd HH:mm:ss.SSS"
      # Locale used for formatting
      time-zone: "GMT+8"

