POST http://localhost:8080/message/save
Content-Type: application/json

{
  "sender": "user@mail.ru",
  "receiver": "ksusha-golubeffa@mail.ru",
  "text": "Я вижу, что ты пишешь, не надо каждую секунду слать смски свои дурацкие"

}


###
