POST http://localhost:8080/user/register
Content-Type: application/json

{
  "username": "ksushagolubeffa",
  "password": "12345ae",
  "passwordRepeat": "12345ae",
  "email": "ksushagolubeffa@mail.ru",
  "birth": "09.12.2003",
  "male": false
}



