POST http://localhost:8080/user/register
Content-Type: application/json

{
  "username": "aabbcc",
  "password": "12345ae",
  "passwordRepeat": "54321",
  "email": "aabbcc@mail.ru",
  "birth": "09.12.2003",
  "male": false
}



